// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxerczfgihpfsgbmptrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZXJjemZnaWhwZnNnYm1wdHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDQ0NTYsImV4cCI6MjA3NDMyMDQ1Nn0.E8N7fLNJLEAcbI5JD3GmOv-KHXuzIG67q5Ob5QFa66A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});